/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as PostsImport } from './routes/posts'
import { Route as LoginImport } from './routes/login'
import { Route as GroupsImport } from './routes/groups'
import { Route as CreateGroupImport } from './routes/createGroup'
import { Route as AccountImport } from './routes/account'
import { Route as IndexImport } from './routes/index'
import { Route as GroupGroupIdIndexImport } from './routes/group/$groupId/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const PostsRoute = PostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const GroupsRoute = GroupsImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRoute,
} as any)

const CreateGroupRoute = CreateGroupImport.update({
  id: '/createGroup',
  path: '/createGroup',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GroupGroupIdIndexRoute = GroupGroupIdIndexImport.update({
  id: '/group/$groupId/',
  path: '/group/$groupId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/createGroup': {
      id: '/createGroup'
      path: '/createGroup'
      fullPath: '/createGroup'
      preLoaderRoute: typeof CreateGroupImport
      parentRoute: typeof rootRoute
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/group/$groupId/': {
      id: '/group/$groupId/'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/createGroup': typeof CreateGroupRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/group/$groupId': typeof GroupGroupIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/createGroup': typeof CreateGroupRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/group/$groupId': typeof GroupGroupIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/createGroup': typeof CreateGroupRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/group/$groupId/': typeof GroupGroupIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/createGroup'
    | '/groups'
    | '/login'
    | '/posts'
    | '/register'
    | '/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/createGroup'
    | '/groups'
    | '/login'
    | '/posts'
    | '/register'
    | '/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/createGroup'
    | '/groups'
    | '/login'
    | '/posts'
    | '/register'
    | '/group/$groupId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CreateGroupRoute: typeof CreateGroupRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRoute
  RegisterRoute: typeof RegisterRoute
  GroupGroupIdIndexRoute: typeof GroupGroupIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CreateGroupRoute: CreateGroupRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRoute,
  RegisterRoute: RegisterRoute,
  GroupGroupIdIndexRoute: GroupGroupIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/account",
        "/createGroup",
        "/groups",
        "/login",
        "/posts",
        "/register",
        "/group/$groupId/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/account": {
      "filePath": "account.jsx"
    },
    "/createGroup": {
      "filePath": "createGroup.jsx"
    },
    "/groups": {
      "filePath": "groups.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/posts": {
      "filePath": "posts.jsx"
    },
    "/register": {
      "filePath": "register.jsx"
    },
    "/group/$groupId/": {
      "filePath": "group/$groupId/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
